/*
  File autogenerated by gengetopt version 2.22.2
  generated with the following command:
  gengetopt --unamed-opts --no-handle-version --no-handle-help --no-handle-error 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help            Print help and exit",
  "  -V, --version         Print version and exit",
  "  -f, --forward         Score forward strand  (default=off)",
  "  -r, --reverse         Score reverse strand  (default=off)",
  "  -b, --both-strands    Score both strands  (default=off)",
  "  -o, --outfile=STRING  Output filename",
  "  -w, --window=STRING   Score window",
  "  -p, --cutoff=FLOAT    Probability cutoff",
  "  -g, --show-gaps       Display alignment with gap  (default=off)",
  "  -s, --predict-strand  Use strand predictor  (default=off)",
  "  -x, --plot            Generate graphical output  (default=off)",
  "  -d, --dinucleotide    Use dinucleotide based z-scores  (default=off)",
  "  -l, --locarnate       Use decision model for structural alignments  \n                          (default=off)",
  "  -n, --no-shuffle      Never do explicit shuffling  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_FLOAT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->forward_given = 0 ;
  args_info->reverse_given = 0 ;
  args_info->both_strands_given = 0 ;
  args_info->outfile_given = 0 ;
  args_info->window_given = 0 ;
  args_info->cutoff_given = 0 ;
  args_info->show_gaps_given = 0 ;
  args_info->predict_strand_given = 0 ;
  args_info->plot_given = 0 ;
  args_info->dinucleotide_given = 0 ;
  args_info->locarnate_given = 0 ;
  args_info->no_shuffle_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->forward_flag = 0;
  args_info->reverse_flag = 0;
  args_info->both_strands_flag = 0;
  args_info->outfile_arg = NULL;
  args_info->outfile_orig = NULL;
  args_info->window_arg = NULL;
  args_info->window_orig = NULL;
  args_info->cutoff_orig = NULL;
  args_info->show_gaps_flag = 0;
  args_info->predict_strand_flag = 0;
  args_info->plot_flag = 0;
  args_info->dinucleotide_flag = 0;
  args_info->locarnate_flag = 0;
  args_info->no_shuffle_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->forward_help = gengetopt_args_info_help[2] ;
  args_info->reverse_help = gengetopt_args_info_help[3] ;
  args_info->both_strands_help = gengetopt_args_info_help[4] ;
  args_info->outfile_help = gengetopt_args_info_help[5] ;
  args_info->window_help = gengetopt_args_info_help[6] ;
  args_info->cutoff_help = gengetopt_args_info_help[7] ;
  args_info->show_gaps_help = gengetopt_args_info_help[8] ;
  args_info->predict_strand_help = gengetopt_args_info_help[9] ;
  args_info->plot_help = gengetopt_args_info_help[10] ;
  args_info->dinucleotide_help = gengetopt_args_info_help[11] ;
  args_info->locarnate_help = gengetopt_args_info_help[12] ;
  args_info->no_shuffle_help = gengetopt_args_info_help[13] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->outfile_arg));
  free_string_field (&(args_info->outfile_orig));
  free_string_field (&(args_info->window_arg));
  free_string_field (&(args_info->window_orig));
  free_string_field (&(args_info->cutoff_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->forward_given)
    write_into_file(outfile, "forward", 0, 0 );
  if (args_info->reverse_given)
    write_into_file(outfile, "reverse", 0, 0 );
  if (args_info->both_strands_given)
    write_into_file(outfile, "both-strands", 0, 0 );
  if (args_info->outfile_given)
    write_into_file(outfile, "outfile", args_info->outfile_orig, 0);
  if (args_info->window_given)
    write_into_file(outfile, "window", args_info->window_orig, 0);
  if (args_info->cutoff_given)
    write_into_file(outfile, "cutoff", args_info->cutoff_orig, 0);
  if (args_info->show_gaps_given)
    write_into_file(outfile, "show-gaps", 0, 0 );
  if (args_info->predict_strand_given)
    write_into_file(outfile, "predict-strand", 0, 0 );
  if (args_info->plot_given)
    write_into_file(outfile, "plot", 0, 0 );
  if (args_info->dinucleotide_given)
    write_into_file(outfile, "dinucleotide", 0, 0 );
  if (args_info->locarnate_given)
    write_into_file(outfile, "locarnate", 0, 0 );
  if (args_info->no_shuffle_given)
    write_into_file(outfile, "no-shuffle", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  return result;
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  FIX_UNUSED (field);
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "forward",	0, NULL, 'f' },
        { "reverse",	0, NULL, 'r' },
        { "both-strands",	0, NULL, 'b' },
        { "outfile",	1, NULL, 'o' },
        { "window",	1, NULL, 'w' },
        { "cutoff",	1, NULL, 'p' },
        { "show-gaps",	0, NULL, 'g' },
        { "predict-strand",	0, NULL, 's' },
        { "plot",	0, NULL, 'x' },
        { "dinucleotide",	0, NULL, 'd' },
        { "locarnate",	0, NULL, 'l' },
        { "no-shuffle",	0, NULL, 'n' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVfrbo:w:p:gsxdln", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->help_given),
              &(local_args_info.help_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "help", 'h',
              additional_error))
            goto failure;
          cmdline_parser_free (&local_args_info);
          return 0;
        
          break;
        case 'V':	/* Print version and exit.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->version_given),
              &(local_args_info.version_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "version", 'V',
              additional_error))
            goto failure;
          cmdline_parser_free (&local_args_info);
          return 0;
        
          break;
        case 'f':	/* Score forward strand.  */
        
        
          if (update_arg((void *)&(args_info->forward_flag), 0, &(args_info->forward_given),
              &(local_args_info.forward_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "forward", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Score reverse strand.  */
        
        
          if (update_arg((void *)&(args_info->reverse_flag), 0, &(args_info->reverse_given),
              &(local_args_info.reverse_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "reverse", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Score both strands.  */
        
        
          if (update_arg((void *)&(args_info->both_strands_flag), 0, &(args_info->both_strands_given),
              &(local_args_info.both_strands_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "both-strands", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Output filename.  */
        
        
          if (update_arg( (void *)&(args_info->outfile_arg), 
               &(args_info->outfile_orig), &(args_info->outfile_given),
              &(local_args_info.outfile_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "outfile", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'w':	/* Score window.  */
        
        
          if (update_arg( (void *)&(args_info->window_arg), 
               &(args_info->window_orig), &(args_info->window_given),
              &(local_args_info.window_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "window", 'w',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Probability cutoff.  */
        
        
          if (update_arg( (void *)&(args_info->cutoff_arg), 
               &(args_info->cutoff_orig), &(args_info->cutoff_given),
              &(local_args_info.cutoff_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "cutoff", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Display alignment with gap.  */
        
        
          if (update_arg((void *)&(args_info->show_gaps_flag), 0, &(args_info->show_gaps_given),
              &(local_args_info.show_gaps_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "show-gaps", 'g',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Use strand predictor.  */
        
        
          if (update_arg((void *)&(args_info->predict_strand_flag), 0, &(args_info->predict_strand_given),
              &(local_args_info.predict_strand_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "predict-strand", 's',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* Generate graphical output.  */
        
        
          if (update_arg((void *)&(args_info->plot_flag), 0, &(args_info->plot_given),
              &(local_args_info.plot_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "plot", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Use dinucleotide based z-scores.  */
        
        
          if (update_arg((void *)&(args_info->dinucleotide_flag), 0, &(args_info->dinucleotide_given),
              &(local_args_info.dinucleotide_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "dinucleotide", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Use decision model for structural alignments.  */
        
        
          if (update_arg((void *)&(args_info->locarnate_flag), 0, &(args_info->locarnate_given),
              &(local_args_info.locarnate_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "locarnate", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Never do explicit shuffling.  */
        
        
          if (update_arg((void *)&(args_info->no_shuffle_flag), 0, &(args_info->no_shuffle_given),
              &(local_args_info.no_shuffle_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "no-shuffle", 'n',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
